# Generated by Django 5.0.7 on 2024-07-14 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte_tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_name', models.CharField(max_length=200)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('responsible', models.CharField(max_length=100)),
                ('reporte_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_tecnico', to='reporte_tecnico.reporte_tecnico')),
            ],
        ),
    ]
