# Generated by Django 5.0.7 on 2024-07-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_movimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_movimiento',
            old_name='movement_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tipo_movimiento',
            name='movement_date',
        ),
    ]
