# Generated by Django 5.0.7 on 2024-07-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_responsable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area_responsable',
            old_name='created_at',
            new_name='fecha_creada',
        ),
        migrations.RenameField(
            model_name='area_responsable',
            old_name='entry_responsible',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='area_responsable',
            old_name='name_responsible',
            new_name='responsable_entrada',
        ),
        migrations.RenameField(
            model_name='area_responsable',
            old_name='output_responsible',
            new_name='responsable_salida',
        ),
    ]
