# Generated by Django 5.0.7 on 2024-07-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristica', '0001_initial'),
        ('categoria', '0001_initial'),
        ('clasificacion', '0001_initial'),
        ('estado', '0001_initial'),
        ('marca', '0001_initial'),
        ('propiedad_baja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prestado_fecha', models.DateTimeField(auto_now_add=True)),
                ('num_inventario', models.IntegerField()),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='caracteristica.caracteristica')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='categoria.categoria')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='clasificacion.clasificacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='estado.estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='marca.marca')),
                ('propiedad_baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='propiedad_baja.propiedad_baja')),
            ],
        ),
    ]
