# Generated by Django 5.0.7 on 2024-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('category', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.CharField(max_length=100)),
                ('characteristic', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.TextField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('bowered', models.CharField(max_length=100)),
                ('inventory_number', models.IntegerField()),
                ('range', models.TextField()),
            ],
        ),
    ]
