# Generated by Django 5.0.7 on 2024-07-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_request', models.TextField()),
                ('authorized', models.BooleanField()),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField()),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('transported_date', models.DateTimeField(auto_now_add=True)),
                ('name_fact', models.CharField(max_length=200)),
            ],
        ),
    ]
