# Generated by Django 5.0.7 on 2024-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_transferencia', models.TextField()),
                ('autorizado', models.BooleanField()),
                ('posicion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizado', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField()),
                ('fecha_aprobado', models.DateTimeField(auto_now_add=True)),
                ('fecha_traspaso', models.DateTimeField(auto_now_add=True)),
                ('nombre_hecho', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
