# Generated by Django 5.0.7 on 2024-07-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='name',
            new_name='nombre',
        ),
    ]
