# Generated by Django 5.0.7 on 2024-07-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_responsable', '0002_rename_created_at_area_responsable_fecha_creada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('codigo', models.IntegerField()),
                ('area_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_responsible', to='area_responsable.area_responsable')),
            ],
        ),
    ]
