# Generated by Django 5.0.7 on 2024-07-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_responsible', '0001_initial'),
        ('local', '0001_initial'),
        ('tipo_movimiento', '0002_rename_movement_name_tipo_movimiento_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.IntegerField()),
                ('responsible', models.TextField()),
                ('area_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_responsible', to='area_responsible.area_responsible')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='local.local')),
                ('tipo_movimientoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_movimiento', to='tipo_movimiento.tipo_movimiento')),
            ],
        ),
    ]
