# Generated by Django 5.0.7 on 2024-07-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('local', '0001_initial'),
        ('tipo_movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='local.local'),
        ),
        migrations.AddField(
            model_name='area',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_movimiento', to='tipo_movimiento.tipo_movimiento'),
        ),
    ]
