# Generated by Django 5.0.7 on 2024-07-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='created_at',
            new_name='fecha_actualizado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='update_at',
            new_name='fecha_crado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='surname',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='telf',
        ),
    ]
