# Generated by Django 5.0.7 on 2024-07-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad', to='propiedad.propiedad'),
        ),
    ]
